version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.35
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14250:14250"
      - "14268:14268"
      - "16686:16686"
      - "14293:14293"
      - "14267:14267"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_HTTP_PORT=9411
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    environment:
      - OTEL_COLLECTOR_ZIPKIN_HTTP_PORT=5775
      - OTEL_COLLECTOR_PROMETHEUS_PORT=8889
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - "--config=/etc/otel-collector-config.yaml"
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  hashing-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - opentelemetry-collector
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - OTEL_SERVICE_NAME=hashing-service
