mode: deployment  
image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
config:
  # receivers: how otel receives data
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  # processors: where data is being processed
  processors:
    batch:
      timeout: 5s
      send_batch_size: 100
  # exports: where otel send data
  exporters:
    otlp:
      endpoint: jaeger-collector:14250
      tls:
        insecure: true
    prometheus:
      endpoint: 0.0.0.0:8889
  # services: processing pipelines
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]