### Length Service Namespace
{{- if .Values.lengthservice.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.lengthservice.service_name }}
---
### Length Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lengthservice.service_name }}
  namespace: {{ .Values.lengthservice.service_name }}
  labels:
    app: {{ .Values.lengthservice.service_name }}
spec:
  replicas: {{ .Values.lengthservice.replicas }}
  revisionHistoryLimit: 10
  strategy:
    type: {{ .Values.lengthservice.deploymentStrategy }}
  selector:
    matchLabels:
      app: {{ .Values.lengthservice.service_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.lengthservice.service_name }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Values.lengthservice.service_name }}
        image: {{ .Values.lengthservice.image.repository }}:{{ .Values.lengthservice.image.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.lengthservice.resources.limits.memory }}
            cpu: {{ .Values.lengthservice.resources.limits.cpu }}
          requests:
            memory: {{ .Values.lengthservice.resources.requests.memory }}
            cpu: {{ .Values.lengthservice.resources.requests.cpu }}
        ports:
        - containerPort: {{ .Values.lengthservice.containerPort }}
        command: ["opentelemetry-instrument", "python3", "main.py"]
        # args:
          # - "--traces_exporter=console,otlp"
          # - "--metrics_exporter=console"
          # - "--service_name=hashing-service"
          # - "--exporter_otlp_endpoint=opentelemetry-opentelemetry-collector.monitoring.svc.cluster.local:4317"
          # - "python3"
          # - "main.py" 
        ports:
        - containerPort: {{ .Values.hashingservice.containerPort }}
        env:
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: http://opentelemetry-opentelemetry-collector.monitoring.svc.cluster.local:4317
          - name: OTEL_SERVICE_NAME
            value: {{ .Values.hashingservice.service_name }}
          - name: OTEL_TRACES_EXPORTER
            value: otlp,console
          - name: OTEL_METRICS_EXPORTER
            value: console
---
### Length Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lengthservice.service_name }}
  namespace: {{ .Values.lengthservice.service_name }}
spec:
  selector:
    app: {{ .Values.lengthservice.service_name }}
  ports:
    - name: {{ .Values.lengthservice.service_name }}
      port: {{ .Values.lengthservice.containerPort }}
      targetPort: {{ .Values.lengthservice.containerPort }}
{{- end }}
